[[pages]]
path = "app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
name = "Fechas"
icon = "ğŸ“…"
is_section = true

# Pages after an `is_section = true` will be indented
[[pages]]
name = "Feriados"

# Unless you explicitly say in_section = false`
[[pages]]
name = "Not in a section"
in_section = false

[[pages]]
name = "Not in a section2"